// The deck's Next app. P0-T6 builds it as the host for the xterm spike; P2-T1 turns it into the
// real deck. The security posture is here from the first commit rather than retrofitted, because
// P0-T7 measured what happens without it: a page at :4949 cannot reach core at :4950 directly at
// all — a port is part of an origin — so the rewrite below is the only route that works
// (RESEARCH.md F.4.2), and a CSP added later would have been written against a broken assumption.
import type { NextConfig } from 'next';
import { CORE_ORIGIN } from './contracts/origins.ts';

// The CSP is NOT here: it needs a per-request nonce, so it is issued by middleware.ts. These are
// the headers that are the same on every response.
const SECURITY_HEADERS = [
  { key: 'X-Frame-Options', value: 'DENY' },
  { key: 'X-Content-Type-Options', value: 'nosniff' },
  { key: 'Referrer-Policy', value: 'no-referrer' },
  { key: 'Permissions-Policy', value: 'clipboard-read=(self)' },
  { key: 'Cache-Control', value: 'no-store' },
];

const nextConfig: NextConfig = {
  reactStrictMode: true,
  // Pinned, because there is a package-lock.json in the home directory above this repo and
  // Turbopack otherwise walks up to it and roots the build outside the project.
  turbopack: { root: import.meta.dirname },
  // The app compiles against the DOM and core/ must not, so they are separate TS projects. Without
  // this, `next build` rewrites the ROOT tsconfig — adding jsx, allowJs and .next types to the
  // config core/ and scripts/ are checked by, which is the leak tsconfig.app.json exists to stop.
  typescript: { tsconfigPath: './tsconfig.app.json' },
  // No telemetry, no external fetches, no remote images — SEC-NET-2.
  images: { unoptimized: true },
  // Next 16 writes an AGENTS.md and a CLAUDE.md into the repo root on first run unless this is
  // off. Nothing generated by a build belongs in a repo whose instruction files are hand-written.
  agentRules: false,
  headers() {
    // Not `/:path*`: that stamps these onto `_next/hmr` too, and adding response headers to a
    // WebSocket upgrade breaks the handshake — the browser reports ERR_INVALID_HTTP_RESPONSE and
    // the dev page never hydrates (RESEARCH.md G.3). Nothing under `_next` is a document.
    //
    // `api/` is excluded for a sharper reason, found by running P1-T9 rather than by reading it:
    // these headers REPLACE a route handler's own, and `Cache-Control: no-store` here silently
    // overwrote the stream's `no-store, no-transform` — the one header that stops Next gzipping an
    // event stream into a single chunk at the end (RESEARCH.md F.6.3, DECISIONS.md D27). Nothing
    // under `api/` is a document either: `/api/core/*` is answered by core, which sets its own
    // `no-store` and `nosniff` on every response, and `/api/stream` sets its own.
    return Promise.resolve([{ source: '/((?!_next|api/).*)', headers: SECURITY_HEADERS }]);
  },
  // The only route from the browser to core. Server-to-server, so no CORS is involved and the
  // token never reaches the page (RESEARCH.md F.4.2, SEC-HTTP-5).
  rewrites() {
    return Promise.resolve([{ source: '/api/core/:path*', destination: `${CORE_ORIGIN}/:path*` }]);
  },
};

export default nextConfig;
