// The deck's Next app. P0-T6 builds it as the host for the xterm spike; P2-T1 turns it into the
// real deck. The security posture is here from the first commit rather than retrofitted, because
// P0-T7 measured what happens without it: a page at :4949 cannot reach core at :4950 directly at
// all — a port is part of an origin — so the rewrite below is the only route that works
// (RESEARCH.md F.4.2), and a CSP added later would have been written against a broken assumption.
//
// **What each value means is in contracts/deck-routes.ts, not here**, and so are the two silent
// regressions the matchers exist to prevent. This file is the wiring; that file is the decision,
// and it is the one `tests/contracts/deck-routes.test.ts` can assert without dragging `next/server`
// into the TypeScript project core/ is checked by.
import type { NextConfig } from 'next';
import { CORE_REWRITE, DOCUMENT_ROUTES, SECURITY_HEADERS } from './contracts/deck-routes.ts';

const nextConfig: NextConfig = {
  reactStrictMode: true,
  // Pinned, because there is a package-lock.json in the home directory above this repo and
  // Turbopack otherwise walks up to it and roots the build outside the project.
  turbopack: { root: import.meta.dirname },
  // The app compiles against the DOM and core/ must not, so they are separate TS projects. Without
  // this, `next build` rewrites the ROOT tsconfig — adding jsx, allowJs and .next types to the
  // config core/ and scripts/ are checked by, which is the leak tsconfig.app.json exists to stop.
  typescript: { tsconfigPath: './tsconfig.app.json' },
  // No telemetry, no external fetches, no remote images — SEC-NET-2. The telemetry half is an
  // environment variable rather than a setting here: `NEXT_TELEMETRY_DISABLED=1`, set by
  // flightdeck.cmd, ci.yml and release.yml, which is every route that builds this app.
  images: { unoptimized: true },
  // Next 16 writes an AGENTS.md and a CLAUDE.md into the repo root on first run unless this is
  // off. Nothing generated by a build belongs in a repo whose instruction files are hand-written.
  agentRules: false,
  // The CSP is NOT here: it needs a per-request nonce, so it is issued by proxy.ts — which is also
  // why that file is proxy.ts and not middleware.ts, since only proxy runs on Node and can read
  // the token file (RESEARCH.md F.6.2, DECISIONS.md D27).
  headers() {
    return Promise.resolve([{ source: DOCUMENT_ROUTES, headers: [...SECURITY_HEADERS] }]);
  },
  rewrites() {
    return Promise.resolve([{ ...CORE_REWRITE }]);
  },
};

export default nextConfig;
