// The `claude logs` fixture — P5a-T4, DECISIONS.md D28.
//
// D28 moved this capture out of P0 and into the task that parses it, on the argument that "a
// fixture captured without a consumer is captured wrong". These are the assertions that argument
// was for: what a terminal frame's scrubber has to preserve is not the SHAPE of a value, it is the
// LENGTH of one, because every glyph advances the cursor a cell and the frame relies on autowrap.
//
// **The golden is the reviewable half of an unreadable fixture.** `logs-blocked.txt` is 330 046
// bytes of scrubbed escape sequences and nobody will ever read it. `logs-blocked.screen.txt` is
// the twenty-five lines it flattens to, committed, and a reviewer can see at a glance that it is a
// Claude Code screen with the identity gone. It is deliberately NOT regenerated by
// `capture-fixtures.mjs`: a golden rewritten by the code it checks proves nothing.
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { HeadlessScreenReader } from '../../core/adapters/xterm/headless-screen-reader.ts';
import { CLAUDE_LOGS_FRAME } from '../../core/ports/screen-reader.ts';
import { condense } from '../../contracts/session-preview.ts';
import { FakeLogger } from '../fakes/fake-logger.ts';

const FIXTURES = join(import.meta.dirname, '..', '..', 'fixtures', 'logs');
const FRAME = readFileSync(join(FIXTURES, 'logs-blocked.txt'), 'utf8');
const GOLDEN = readFileSync(join(FIXTURES, 'logs-blocked.screen.txt'), 'utf8');

describe('the scrubbed claude logs frame', () => {
  it('is the shape F.2.5 measured — a frame, not a log', () => {
    expect(Buffer.byteLength(FRAME)).toBe(330_046);
    expect(FRAME.split('\n')).toHaveLength(4724);
    // eslint-disable-next-line no-control-regex -- counting escape sequences needs ESC.
    expect(FRAME.match(/\u001b\[[0-?]*[ -/]*[@-~]/gu)).toHaveLength(10_483);
  });

  it('kept its CRLFs, which git would otherwise have rewritten to LF', () => {
    // `.gitattributes` says `* text=auto eol=lf`, and that rule applied to a frame steps the whole
    // screen right on every line: CRLF returns to column 0 and drops a row, a bare LF drops a row
    // and stays put. `fixtures/**/*.txt -text` is what exempts it, and this is what notices if
    // that line is ever removed (RESEARCH.md G.35).
    expect(FRAME.match(/\r\n/gu)).toHaveLength(4723);
    expect(FRAME.match(/(?<!\r)\n/gu)).toBeNull();
  });

  it('carries no identity — not the account name, not a project folder', () => {
    // Every alphanumeric run in the frame is replaced, so this is a check that the rule RAN rather
    // than a list of things to remember. `Claude` is in it because the banner prints it, and a
    // scrubber that spared "harmless" words is the F.7.8 mistake in a new suit.
    for (const leak of ['belas', 'Users', 'AppData', 'Claude', 'Anthropic', 'flightdeck']) {
      expect(FRAME).not.toContain(leak);
    }
  });

  it('kept the chrome glyphs, which are structure and not identity', () => {
    for (const glyph of ['─', '█', '▐', '·', '⏸', '❯']) expect(FRAME).toContain(glyph);
  });

  it('flattens to the committed golden', async () => {
    const rows = await new HeadlessScreenReader(new FakeLogger()).read(FRAME, CLAUDE_LOGS_FRAME);

    expect(`${condense(rows).join('\n')}\n`).toBe(GOLDEN);
  });
});

describe('the golden screen', () => {
  it('is a screen a reviewer can read — a banner, a conversation and a status bar', () => {
    const lines = GOLDEN.split('\n');

    expect(lines.length).toBeGreaterThan(15);
    expect(lines.length).toBeLessThan(40);
    // The prompt box and the status bar, which are the two rules and the gauge at the bottom.
    expect(GOLDEN).toContain('─────');
    expect(GOLDEN).toContain('██');
  });

  it('is plain text with nothing left to interpret (SEC-UI-2)', () => {
    expect(GOLDEN).not.toContain('\u001b');
    expect(GOLDEN).not.toContain('\r');
  });

  it('has no line wider than the frame it came off', () => {
    for (const line of GOLDEN.split('\n')) {
      expect(line.length).toBeLessThanOrEqual(CLAUDE_LOGS_FRAME.columns);
    }
  });
});
